from Tkinter import *
import tkMessageBox
c=0;d1=[];k='';Q1=[];s=0;buy=[]
c1,d,e,f,g,h,i,j,k,l,m='','','','','','','','','','',''
city,postcode,country,state,password,confirmpassword=dict(),dict(),dict(),dict(),dict(),dict()
firstname,lastname,email,address,telephone=dict(),dict(),dict(),dict(),dict()
Q=dict()
h={"Adenium Baby Pink - Adenium obesum":275,"Euphorbia Orange Plant":200,"Marigold Yellow":300,"Hibiscus-Dwarf":300,"Arabian Jasmine":300,"Peace-rose":350,"Aster amellus":100,"Geranium dissectum":250,"Vinca minor":100,"Zinnia plant":100,"Petunia Violet":300,"Salvia Red":100,"Pink anthurium":100,"Pachira Plant":100,"Phalaenopsis amabilis":100,"Aglaonema plant":100,"Anthurium Red":100,"Bauhinia Variegata":100,"Aegle marmelos":100,"Ageratum plant":100,"Litchi chinensis":100,"Brussels sprout":100,"Anemone Bulbs":100,"Lavender Planter":100,"Tower Planter Black":100,"Hexa Planter No.1 Brown":125,"Green Valley Planter":100,"Apple Valley Planter":100,"Self Watering Pots":100,"Agricultural Fertilizers":100,"Green Gold - Organic":100,"Bio Organic Granuels":100,"Bonsai Potting Mix":100,"Cow Manure":100}
D={"Adenium Baby Pink - Adenium obesum":"A001","Tagar Double Plant - Crape Jasmine":"A002","Euphorbia Orange Plant":"A003","Marigold Yellow":"A004","Hibiscus-Dwarf":"A005","Arabian Jasmine":"A006","Peace-rose":"A007","Amaryllis-Jersy Lily":"A008","Aster amellus":"A009","Geranium dissectum":"A010","Vinca minor":"A011","Zinnia plant":"A012","Carnation Clove-pink":"A013","Petunia Violet":"A014","Dahlia Red Plant":"A015","Salvia Red":"A016","Pink anthurium":"A017","Pachira Plant":"A018","Phalaenopsis amabilis":"A019","Aglaonema plant":"A020","Anthurium Red":"A021","Bauhinia Variegata":"A022","Aegle marmelos":"A023","Ageratum plant":"A024","Litchi chinensis":"A025","Brussels sprout":"A026","Anemone Bulbs":"A027","Zephyranhes":"A028","Lavender Planter":"A029","Tower Planter Black":"A030","Hexa Planter No.1 Brown":"A031","Green Valley Planter":"A032","Apple Valley Planter":"A033","Self Watering Pots":"A034","Agricultural Fertilizers":"A035","Green Gold - Organic":"A036","Bio Organic Granuels":"A037","Bonsai Potting Mix":"A038","Cow Manure":"A039"}
P={"Adenium Baby Pink - Adenium obesum":479,"Tagar Double Plant - Crape Jasmine":249,"Euphorbia Orange Plant":299,"Marigold Yellow":250,"Hibiscus-Dwarf":529,"Arabian Jasmine":219,"Peace-rose":250,"Amaryllis-Jersy Lily":279,"Aster amellus":185,"Geranium dissectum":329,"Vinca minor":189,"Zinnia plant":279,"Carnation Clove-pink":379,"Petunia Violet":175,"Dahlia Red Plant":319,"Salvia Red":209,"Pink anthurium":699,"Pachira Plant":1599,"Phalaenopsis amabilis":1329,"Aglaonema plant":799,"Anthurium Red":699,"Bauhinia Variegata":279,"Aegle marmelos":1330,"Ageratum plant":90,"Litchi chinensis":1900,"Brussels sprout":50,"Anemone Bulbs":399,"Zephyranhes":120,"Lavender Planter":679,"Tower Planter Black":599,"'Hexa Planter No.-1 Brown'":299,"Green Valley Planter":549,"Apple Valley Planter":1499,"Self Watering Pots":979,"Agricultural Fertilizers":229,"Green Gold - Organic":260,"Bio Organic Granuels":189,"Bonsai Potting Mix":249,"Cow Manure":480}
A={"Adenium Baby Pink - Adenium obesum":100,"Tagar Double Plant - Crape Jasmine":100,"Euphorbia tan1 Plant":100,"Marigold Yellow":100,"Hibiscus-Dwarf":100,"Arabian Jasmine":100,"Peace-rose":100,"Amaryllis-Jersy Lily":100,"Aster amellus":100,"Geranium dissectum":100,"Vinca minor":100,"Zinnia plant":100,"Carnation Clove-pink":100,"Petunia Violet":100,"Dahlia Red Plant":100,"Salvia Red":100,"Pink anthurium":100,"Pachira Plant":100,"Phalaenopsis amabilis":100,"Aglaonema plant":100,"Anthurium Red":100,"Bauhinia Variegata":100,"Aegle marmelos":100,"Ageratum plant":100,"Litchi chinensis":100,"Brussels sprout":100,"Anemone Bulbs":100,"Zephyranhes":100,"Lavender Planter":100,"Tower Planter Black":100,"'Hexa Planter No.-1 Brown'":100,"Green Valley Planter":100,"Apple Valley Planter":100,"Self Watering Pots":100,"Agricultural Fertilizers":100,"Green Gold - Organic":100,"Bio Organic Granuels":100,"Bonsai Potting Mix":100,"Cow Manure":100}
def button(x):
    global k
    if x in ['Lavender Planter','Tower Planter Black','Hexa Planter No.-1 Brown','Green Valley Planter','Apple Valley Planter','Self Watering Pots','Agricultural Fertilizers','Green Gold - Organic','Bonsai Potting Mix','Bio Organic Granuels','Cow Manure']:
        top=Toplevel()
        Label(top,text="PLANT ID:"+D[str(x)],font=('Consolas',25)).place(x=375,y=95)
        Label(top,text="AVAILABILITY:"+str(A[str(x)]),font=('Consolas',25)).place(x=675,y=95)
        Label(top,text="PRICE:Rs"+str(P[str(x)]),font=('Consolas',25)).place(x=375,y=160)
        Label(top,text="Quantity:",font=('Consolas',25)).place(x=675,y=160)
        top.geometry("1000x600")
        k=Entry(top,justify="center");k.insert(END,"1")
        k.place(x=850,y=175,width=50)
        Label(top,text=str(x),font=('Consolas',35)).place(x=h[str(x)],y=10)
        filename = PhotoImage(file = (str(x)+".gif"))
        image =Label(top,image=filename)
        image.place(x=20, y=75)
        Button(top,text="Buy Now",font=('Consolas',20),command=lambda:buynow(x)).place(x=525,y=230)
        top.mainloop()
    else:
        top=Toplevel()
        Label(top,text="PLANT ID:"+D[str(x)],font=('Consolas',25)).place(x=375,y=95)
        Label(top,text="AVAILABILITY:"+str(A[str(x)]),font=('Consolas',25)).place(x=675,y=95)
        Label(top,text="PRICE:Rs"+str(P[str(x)]),font=('Consolas',25)).place(x=375,y=160)
        Label(top,text="Quantity:",font=('Consolas',25)).place(x=675,y=160)
        top.geometry("1000x1000")
        k=Entry(top,justify="center");k.insert(END,"1")
        k.place(x=850,y=175,width=50)
        Label(top,text=str(x),font=('Consolas',35)).place(x=h[str(x)],y=10)
        filename = PhotoImage(file = (str(x)+".gif"))
        image =Label(top,image=filename)
        image.place(x=20, y=75)
        Button(top,text="Buy Now",font=('Consolas',20),command=lambda:buynow(x)).place(x=525,y=230)
        file = open(str(x)+".txt","r")
        read1=file.readlines()
        for i in range(13):
            Label(top,text=read1[i],font=('Consolas',18)).place(x=0,y=(300+i*30))
        top.mainloop()
def afp(root):
    root.destroy()
    a=Toplevel()
    a.configure(bg='orange')
    a.title("Annual Flowering Plants")
    a.geometry("1000x1000")
    Button(a,text='<<<Back',font=('Consolas',15),command=lambda:main(a)).place(x=0,y=0)
    Label(a,text="Annual Flowering Plants",font=('Consolas',35),bg='orange').place(x=200,y=0)
    Label(a,text='Adenium Baby Pink',height=2,font=('Consolas',15),bg='orange').place(x=80,y=90)
    Label(a,text='Euphorbia tan1 Plant',height=2,font=('Consolas',15),bg='orange').place(x=430,y=90)
    Label(a,text='Marigold Yellow',height=2,font=('Consolas',15),bg='orange').place(x=770,y=90)
    Label(a,text='Hibiscus-Dwarf',height=2,font=('Consolas',15),bg='orange').place(x=100,y=415)
    Label(a,text='Arabian Jasmine',height=2,font=('Consolas',15),bg='orange').place(x=430,y=415)
    Label(a,text='Peace-rose',height=2,font=('Consolas',15),bg='orange').place(x=760,y=415)
    filename=PhotoImage(file = "Adenium Baby Pink - Adenium obesum.gif")
    image=Button(a,image=filename,command=lambda:button("Adenium Baby Pink - Adenium obesum"))
    image.place(x=25, y=150)
    filename1=PhotoImage(file = "Euphorbia orange Plant.gif")
    image1=Button(a,image=filename1,command=lambda:button("Euphorbia Orange Plant"))
    image1.place(x=400, y=150)
    filename2=PhotoImage(file = "Marigold Yellow.gif")
    image2=Button(a,image=filename2,command=lambda:button("Marigold Yellow"))
    image2.place(x=740, y=150)
    filename3=PhotoImage(file = "Hibiscus-Dwarf.gif")
    image3=Button(a,image=filename3,command=lambda:button("Hibiscus-Dwarf"))
    image3.place(x=25, y=470)
    filename4=PhotoImage(file = "Arabian Jasmine.gif")
    image4=Button(a,image=filename4,command=lambda:button("Arabian Jasmine"))
    image4.place(x=380, y=470)
    filename5=PhotoImage(file = "Peace-rose.gif")
    image5=Button(a,image=filename5,command=lambda:button("Peace-rose"))
    image5.place(x=675, y=470)
    a.mainloop()
def sp(root):
    root.destroy()
    a=Toplevel()
    a.configure(bg='PaleGreen1')
    a.title("Seasonal Plants")
    a.geometry("1000x1000")
    Button(a,text='<<<Back',font=('Consolas',15),command=lambda:main(a)).place(x=0,y=0)
    Label(a,text="Seasonal Plants",font=('Consolas',35),bg='PaleGreen1').place(x=300,y=0)
    Label(a,text='Petunia Violet',height=2,font=('Consolas',15),bg='PaleGreen1').place(x=75,y=95)
    Label(a,text='Geranium Dissectum',height=2,font=('Consolas',15),bg='PaleGreen1').place(x=390,y=95)
    Label(a,text='Vinca Minor',height=2,font=('Consolas',15),bg='PaleGreen1').place(x=730,y=95)
    Label(a,text='Zinnia Plant',height=2,font=('Consolas',15),bg='PaleGreen1').place(x=100,y=415)
    Label(a,text='Aster Amellus',height=2,font=('Consolas',15),bg='PaleGreen1').place(x=440,y=415)
    Label(a,text='Salvia Red',height=2,font=('Consolas',15),bg='PaleGreen1').place(x=780,y=415)
    filename=PhotoImage(file = "Petunia Violet.gif")
    image=Button(a,image=filename,command=lambda:button("Petunia Violet"))
    image.place(x=25, y=150)
    filename1=PhotoImage(file = "Geranium dissectum.gif")
    image1=Button(a,image=filename1,command=lambda:button("Geranium dissectum"))
    image1.place(x=370, y=150)
    filename2=PhotoImage(file = "Vinca minor.gif")
    image2=Button(a,image=filename2,command=lambda:button("Vinca minor"))
    image2.place(x=650, y=150)
    filename3=PhotoImage(file = "Zinnia plant.gif")
    image3=Button(a,image=filename3,command=lambda:button("Zinnia plant"))
    image3.place(x=25, y=470)
    filename4=PhotoImage(file = "Aster amellus.gif")
    image4=Button(a,image=filename4,command=lambda:button("Aster amellus"))
    image4.place(x=400, y=470)
    filename5=PhotoImage(file = "Salvia Red.gif")
    image5=Button(a,image=filename5,command=lambda:button("Salvia Red"))
    image5.place(x=700, y=470)
    a.mainloop()
def gp(root):
    root.destroy()
    a=Toplevel()
    a.configure(bg='light blue')
    a.title("Gift Plants")
    a.geometry("1000x1000")
    Button(a,text='<<<Back',font=('Consolas',15),command=lambda:main(a)).place(x=0,y=0)
    Label(a,text="Gift Plants",font=('Consolas',35),bg='light blue').place(x=350,y=0)
    Label(a,text='Pink Anthurium',height=2,font=('Consolas',15),bg='light blue').place(x=90,y=95)
    Label(a,text='Phalaenopsis Amabilis',height=2,font=('Consolas',15),bg='light blue').place(x=385,y=95)
    Label(a,text='Pachira Plant',height=2,font=('Consolas',15),bg='light blue').place(x=730,y=95)
    Label(a,text='Aglaonema Plant',height=2,font=('Consolas',15),bg='light blue').place(x=280,y=415)
    Label(a,text='Anthurium Red',height=2,font=('Consolas',15),bg='light blue').place(x=585,y=415)
    filename=PhotoImage(file = "Pink anthurium.gif")
    image=Button(a,image=filename,command=lambda:button("Pink anthurium"))
    image.place(x=25, y=150)
    filename1=PhotoImage(file = "Phalaenopsis amabilis.gif")
    image1=Button(a,image=filename1,command=lambda:button("Phalaenopsis amabilis"))
    image1.place(x=365, y=150)
    filename2=PhotoImage(file = "Pachira Plant.gif")
    image2=Button(a,image=filename2,command=lambda:button("Pachira Plant"))
    image2.place(x=670, y=150)
    filename3=PhotoImage(file = "Aglaonema plant.gif")
    image3=Button(a,image=filename3,command=lambda:button("Aglaonema plant"))
    image3.place(x=225, y=470)
    filename4=PhotoImage(file = "Anthurium Red.gif")
    image4=Button(a,image=filename4,command=lambda:button("Anthurium Red"))
    image4.place(x=525, y=470)
    a.mainloop()
def sb(root):
    root.destroy()
    a=Toplevel()
    a.configure(bg='tomato2')
    a.title("Seeds and Bulbs")
    a.geometry("1000x1000")
    Button(a,text='<<<Back',font=('Consolas',15),command=lambda:main(a)).place(x=0,y=0)
    Label(a,text="Seeds and Bulbs",font=('Consolas',35),bg='tomato2').place(x=300,y=0)
    Label(a,text='Bauhinia Variegata',height=2,font=('Consolas',15),bg='tomato2').place(x=25,y=95)
    Label(a,text='Aegle Marmelos',height=2,font=('Consolas',15),bg='tomato2').place(x=400,y=95)
    Label(a,text='Ageratum Plant',height=2,font=('Consolas',15),bg='tomato2').place(x=775,y=95)
    Label(a,text='Litchi Chinensis',height=2,font=('Consolas',15),bg='tomato2').place(x=70,y=415)
    Label(a,text='Brussels Sprout',height=2,font=('Consolas',15),bg='tomato2').place(x=440,y=415)
    Label(a,text='Anemone Bulbs',height=2,font=('Consolas',15),bg='tomato2').place(x=780,y=415)
    filename=PhotoImage(file = "Bauhinia Variegata.gif")
    image=Button(a,image=filename,command=lambda:button("Bauhinia Variegata"))
    image.place(x=25, y=150)
    filename1=PhotoImage(file = "Aegle marmelos.gif")
    image1=Button(a,image=filename1,command=lambda:button("Aegle marmelos"))
    image1.place(x=320, y=150)
    filename2=PhotoImage(file = "Ageratum plant.gif")
    image2=Button(a,image=filename2,command=lambda:button("Ageratum plant"))
    image2.place(x=750, y=150)
    filename3=PhotoImage(file = "Litchi chinensis.gif")
    image3=Button(a,image=filename3,command=lambda:button("Litchi chinensis"))
    image3.place(x=25, y=470)
    filename4=PhotoImage(file = "Brussels sprout.gif")
    image4=Button(a,image=filename4,command=lambda:button("Brussels sprout"))
    image4.place(x=400, y=470)
    filename5=PhotoImage(file = "Anemone Bulbs.gif")
    image5=Button(a,image=filename5,command=lambda:button("Anemone Bulbs"))
    image5.place(x=750, y=470)
    a.mainloop()
def pp(root):
    root.destroy()
    a=Toplevel()
    a.configure(bg='gold')
    a.title("Pots and Planters")
    a.geometry("1000x1000")
    Button(a,text='<<<Back',font=('Consolas',15),command=lambda:main(a)).place(x=0,y=0)
    Label(a,text="Pots and Planters",font=('Consolas',35),bg='gold').place(x=300,y=0)
    Label(a,text='Lavender Planter',height=2,font=('Consolas',15),bg='gold').place(x=40,y=95)
    Label(a,text='Tower Planter Black',height=2,font=('Consolas',15),bg='gold').place(x=350,y=95)
    Label(a,text='Hexa Planter No.1 Brown',height=2,font=('Consolas',15),bg='gold').place(x=675,y=95)
    Label(a,text='Green Valley Planter',height=2,font=('Consolas',15),bg='gold').place(x=15,y=415)
    Label(a,text='Apple Valley Planter',height=2,font=('Consolas',15),bg='gold').place(x=390,y=415)
    Label(a,text='Self Watering Pots',height=2,font=('Consolas',15),bg='gold').place(x=755,y=415)
    filename=PhotoImage(file = "Lavender Planter.gif")
    image=Button(a,image=filename,command=lambda:button("Lavender Planter"))
    image.place(x=25, y=150)
    filename1=PhotoImage(file = "Tower Planter Black.gif")
    image1=Button(a,image=filename1,command=lambda:button("Tower Planter Black"))
    image1.place(x=350, y=150)
    filename2=PhotoImage(file = "Hexa Planter No. - 1 Brown.gif")
    image2=Button(a,image=filename2,command=lambda:button("'Hexa Planter No.-1 Brown'"))
    image2.place(x=700, y=150)
    filename3=PhotoImage(file = "Green Valley Planter.gif")
    image3=Button(a,image=filename3,command=lambda:button("Green Valley Planter"))
    image3.place(x=25, y=470)
    filename4=PhotoImage(file = "Apple Valley Planter.gif")
    image4=Button(a,image=filename4,command=lambda:button("Apple Valley Planter"))
    image4.place(x=375, y=470)
    filename5=PhotoImage(file = "Self Watering Pots.gif")
    image5=Button(a,image=filename5,command=lambda:button("Self Watering Pots"))
    image5.place(x=750, y=470)
    a.mainloop()
def fz(root):
    root.destroy()
    a=Toplevel()
    a.title("Fertilizers")
    a.configure(bg='sandy brown')
    a.geometry("1000x1000")
    Button(a,text='<<<Back',font=('Consolas',15),command=lambda:main(a)).place(x=0,y=0)
    Label(a,text="Fertilizers",font=('Consolas',35),bg='sandy brown').place(x=350,y=0)
    Label(a,text='Agricultural Fertilizers',height=2,font=('Consolas',15),bg='sandy brown').place(x=40,y=95)
    Label(a,text='Green Gold - Organic',height=2,font=('Consolas',15),bg='sandy brown').place(x=420,y=95)
    Label(a,text='Bonsai Potting Mix',height=2,font=('Consolas',15),bg='sandy brown').place(x=760,y=95)
    Label(a,text='Bio Organic Granuels',height=2,font=('Consolas',15),bg='sandy brown').place(x=240,y=415)
    Label(a,text='Cow Manure',height=2,font=('Consolas',15),bg='sandy brown').place(x=585,y=415)
    filename=PhotoImage(file = "Agricultural Fertilizers.gif")
    image=Button(a,image=filename,command=lambda:button("Agricultural Fertilizers"))
    image.place(x=25, y=150)
    filename1=PhotoImage(file = "Green Gold - Organic.gif")
    image1=Button(a,image=filename1,command=lambda:button("Green Gold - Organic"))
    image1.place(x=415, y=150)
    filename2=PhotoImage(file = "Bonsai Potting Mix.gif")
    image2=Button(a,image=filename2,command=lambda:button("Bonsai Potting Mix"))
    image2.place(x=750, y=150)
    filename3=PhotoImage(file = "Bio Organic Granuels.gif")
    image3=Button(a,image=filename3,command=lambda:button("Bio Organic Granuels"))
    image3.place(x=250, y=470)
    filename4=PhotoImage(file = "Cow Manure.gif")
    image4=Button(a,image=filename4,command=lambda:button("Cow Manure"))
    image4.place(x=525, y=470)
    a.mainloop()

def select(x):
    global p
    p=x.get()
    button(p)
    
def main(w):
    global h
    w.destroy()
    r=Tk()
    r.withdraw()
    root= Toplevel()
    root.configure(bg='SkyBlue1')
    root.title("Main Page")
    root.geometry("1000x1000")
    Label(root,text="Quick Search",font=('Consolas',15),bg='SkyBlue1').place(x=380,y=55)
    a3=Entry(root,width=60)
    a3.place(x=275,y=90)
    global x
    a4=Button(root,text="Search",font=('Consolas',10),command=lambda:button(a3.get()),bg='yellow3')
    a4.place(x=425,y=110)
    mb=Menubutton(root,text="\/",relief=RAISED)
    mb.grid()
    mb.menu = Menu ( mb, tearoff = 0 )
    mb["menu"] = mb.menu
    v=h.keys()
    var=StringVar()
    for i in range(len(v)):
        mb.menu.add_radiobutton(label=v[i],variable=var,value=v[i],command=lambda:button(var.get()))
    mb.place(x=616,y=87)
    Button(root,text="Log In",font=('Consolas',10),command=lambda:Plants(root),bg='yellow3').place(x=940,y=85)
    Button(root,text="Sign Up",font=('Consolas',10),command=lambda:signup(root),bg='yellow3').place(x=870,y=85)
    Label(root,text="Call:7358218210",font=('Consolas',15),bg='SkyBlue1').place(x=705,y=85)
    Label(root,text="All India Delivery",font=('Consolas',15),bg='SkyBlue1').place(x=10,y=85)
    Label(root,text="Top Picks",font=('Consolas',30),bg='SkyBlue1').place(x=400,y=135)
    Label(root,text='Annual Flowering Plants',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=75,y=190)
    Label(root,text='Seosonal Plants',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=440,y=190)
    Label(root,text='Gift Plants',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=770,y=190)
    Label(root,text='Seeds and Bulbs',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=120,y=415)
    Label(root,text='Pots and Planters',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=420,y=415)
    Label(root,text='Fertilizers',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=760,y=415)
    Button(root,text='Click for more...',command=lambda:afp(root),bg='yellow3').place(x=180,y=375)
    Button(root,text='Click for more...',command=lambda:sp(root),bg='yellow3').place(x=490,y=375)
    Button(root,text='Click for more...',command=lambda:gp(root),bg='yellow3').place(x=820,y=375)
    Button(root,text='Click for more...',command=lambda:sb(root),bg='yellow3').place(x=180,y=600)
    Button(root,text='Click for more...',command=lambda:pp(root),bg='yellow3').place(x=515,y=600)
    Button(root,text='Click for more...',command=lambda:fz(root),bg='yellow3').place(x=820,y=600)
    filename=PhotoImage(file = "Hibiscus-Dwarf1.gif")
    image=Button(root,image=filename,command=lambda:button("Hibiscus-Dwarf"))
    image.place(x=30, y=250)
    filename1=PhotoImage(file = "Peace-rose1.gif")
    image1=Button(root,image=filename1,command=lambda:button("Peace-rose"))
    image1.place(x=200, y=250)
    filename2=PhotoImage(file = "Aster amellus1.gif")
    image2=Button(root,image=filename2,command=lambda:button("Aster amellus"))
    image2.place(x=380, y=250)
    filename3=PhotoImage(file = "Zinnia plant1.gif")
    image3=Button(root,image=filename3,command=lambda:button("Zinnia plant"))
    image3.place(x=505, y=250)
    filename4=PhotoImage(file = "Pachira Plant1.gif")
    image4=Button(root,image=filename4,command=lambda:button("Pachira Plant"))
    image4.place(x=680, y=250)
    filename5=PhotoImage(file = "Pink anthurium1.gif")
    image5=Button(root,image=filename5,command=lambda:button("Pink anthurium"))
    image5.place(x=830, y=250)
    filename6=PhotoImage(file = "Brussels sprout1.gif")
    image6=Button(root,image=filename6,command=lambda:button("Brussels sprout"))
    image6.place(x=60, y=470)
    filename7=PhotoImage(file = "Litchi chinensis1.gif")
    image7=Button(root,image=filename7,command=lambda:button("Litchi chinensis"))
    image7.place(x=200, y=470)
    filename8=PhotoImage(file = "Apple Valley Planter1.gif")
    image8=Button(root,image=filename8,command=lambda:button("Apple Valley Planter"))
    image8.place(x=390, y=470)
    filename9=PhotoImage(file = "Lavender Planter1.gif")
    image9=Button(root,image=filename9,command=lambda:button("Lavender Planter"))
    image9.place(x=535, y=470)
    filename10=PhotoImage(file = "Cow Manure1.gif")
    image10=Button(root,image=filename10,command=lambda:button("Cow Manure"))
    image10.place(x=690, y=470)
    filename11=PhotoImage(file = "Green Gold - Organic1.gif")
    image11=Button(root,image=filename11,command=lambda:button("Green Gold - Organic"))
    image11.place(x=840, y=470)
    root.mainloop()

def created(a):
    global s;global c1;global d;global e;global f;global g;global h;global i;global j;global k;global l;global m
    a.destroy()
    s+=1
    b=Tk()
    b.geometry("500x400")
    Label(b,text="Your Account Has Been Created!",font=('Consolas',20)).place(x=30,y=0)
    Label(b,text="Congratulations! Your new account has been successfully created!",font=('Consolas',10)).place(x=20,y=60)
    Label(b,text="You can now take advantage of member privileges to enhance your online",font=('Consolas',10)).place(x=0,y=80)
    Label(b,text="shopping experience with us.If you have ANY questions about the",font=('Consolas',10)).place(x=0,y=100)
    Label(b,text="operation of this online shop, please e-mail the store owner.",font=('Consolas',10)).place(x=0,y=120)
    Button(b,text="Continue",font=('Consolas',15),command=lambda:Plants(b)).place(x=380,y=150)

def signup(w):
    w.destroy()
    def doc(a,b1,c1,d1,e1,f1,g1,h1,i1,j1):
        f=open("Doc.txt",'a+')
        f2=open('admin.txt','a+')
        a3='admin'
        p3='admin'
        r=a3+'\n'+p3
        f2.write(r)
        m1=n.get()
        m2=n2.get()
        m3=n3.get()
        m4=n4.get()
        m5=n5.get()
        m6=n6.get()
        m7=n7.get()
        m8=n8.get()
        m9=n9.get()
        m10=n10.get()
        m11=n11.get()
        t=m1+','+m2+','+m3+','+m4+','+m5+','+m6+',' +m7+','+m8+','+m9+','+m10+'\n'
        f.write(t)
        if m10!=m11:
           tkMessageBox.showerror(title='Invalid password',message='Password did not match')
        elif m1=='':
            tkMessageBox.showerror(title='Invalid',message='Please enter First name')
        elif m2=='':
            tkMessageBox.showerror(title='Invalid',message='Please enter Last name')
        elif m3=='':
            tkMessageBox.showerror(title='Invalid',message='Please enter  a valid Email ID')
        elif m4.isdigit()==False:
             tkMessageBox.showerror(title='Invalid Phone Number',message='Please enter a valid Phone Number')
        elif m5=='':
            tkMessageBox.showerror(title='Invalid ',message='Please enter Adderess')
        elif m6=='':
            tkMessageBox.showerror(title='Invalid',message='Please enter City')
        elif m7.isdigit()==False:
            tkMessageBox.showerror(title='Invalid Post Code',message='Please enter a valid Post Code')
        elif m8=='':
            tkMessageBox.showerror(title='Invalid',message='Please enter Country')
        elif m9=='':
            tkMessageBox.showerror(title='Invalid ',message='Please enter State')
        
        f.close()
    a=Toplevel()
    a.configure(bg='orchid1')
    n=StringVar()
    n2=StringVar()
    n3=StringVar()
    n4=StringVar()
    n5=StringVar()
    n6=StringVar()
    n7=StringVar()
    n8=StringVar()
    n9=StringVar()
    n10=StringVar()
    n11=StringVar()
    a.geometry("800x800")
    Label(a,text="If you already have an account with us, please login at the login page.",font=('Consolas',15),bg='orchid1').place(x=10,y=70)
    Button(a,text="Login",font=('Consolas',15),command=lambda:Plants(a),bg="SteelBlue2").place(x=350,y=120)
    Label(a,text="Register Account",font=('Consolas',35),bg='orchid1').place(x=200,y=0)
    Label(a,text="Your Personal Details",font=('Consolas',25),bg='orchid1').place(x=220,y=175)
    b=Label(a,text='First Name',font=('Consolas',15),bg='orchid1').place(x=10,y=225)
    b1=Entry(a,textvariable=n).place(x=150,y=230,width=150)
    c=Label(a,text='Last Name',font=('Consolas',15),bg='orchid1').place(x=400,y=225)
    c1=Entry(a,textvariable=n2).place(x=530,y=230,width=150)
    d=Label(a,text='E-mail',font=('Consolas',15),bg='orchid1').place(x=10,y=275)
    d1=Entry(a,textvariable=n3).place(x=150,y=280,width=150)
    e=Label(a,text='Telephone',font=('Consolas',15),bg='orchid1').place(x=400,y=275)
    e1=Entry(a,textvariable=n4).place(x=530,y=280,width=150)
    f=Label(a,text="Your Address",font=('Consolas',25),bg='orchid1').place(x=290,y=320)
    Label(a,text='Address',font=('Consolas',15),bg='orchid1').place(x=10,y=380)
    f1=Entry(a,textvariable=n5).place(x=150,y=385,width=150)
    g=Label(a,text='City',font=('Consolas',15),bg='orchid1').place(x=400,y=380)
    g1=Entry(a,textvariable=n6).place(x=530,y=385,width=150)
    h=Label(a,text='Post Code',font=('Consolas',15),bg='orchid1').place(x=10,y=420)
    h1=Entry(a,textvariable=n7).place(x=150,y=425,width=150)
    i=Label(a,text='Country',font=('Consolas',15),bg='orchid1').place(x=400,y=420)
    i1=Entry(a,textvariable=n8).place(x=530,y=425,width=150)
    j=Label(a,text='State',font=('Consolas',15),bg='orchid1').place(x=250,y=475)
    j1=Entry(a,textvariable=n9).place(x=350,y=480,width=150)
    k=Label(a,text="Your Password",font=('Consolas',25),bg='orchid1').place(x=285,y=520)
    Label(a,text='Password',font=('Consolas',15),bg='orchid1').place(x=10,y=575)
    k1=Entry(a,show='*',textvariable=n10).place(x=150,y=580,width=150)
    l=Label(a,text='Confirm Password',font=('Consolas',15),bg='orchid1').place(x=350,y=575)
    l1=Entry(a,show='*',textvariable=n11).place(x=550,y=580,width=150)
    var1=IntVar()
    Checkbutton(a,text="I have read and agree to the Privacy Policy",variable=var1,font=('Consolas',15),bg='orchid1').place(x=125,y=620)
    r=Button(a,text="Verify",bg="SteelBlue2",command=lambda: doc(a,b1,c1,d1,e1,f1,g1,h1,i1,j1),font=('Consolas',18));r.place(x=650,y=640)
    Button(a,text='Continue',bg="SteelBlue2",command=lambda:created(a),font=('Consolas',18)).place(x=650,y=690)
    a.mainloop()

def afterlogin(w):
      global h;global m1
      w.destroy()
      i=Tk()
      i.withdraw()
      root2 = Toplevel()
      root2.configure(bg='SkyBlue1')
      root2.title("Main Page")
      root2.geometry("1000x1000")
      Label(root2,text="Quick Search",font=('Consolas',15),bg='SkyBlue1').place(x=380,y=55)
      a3=Entry(root2,width=60)
      a3.place(x=275,y=90)
      a4=Button(root2,text="Search",font=('Consolas',10),bg='yellow3',command=lambda:button(a3.get()))
      a4.place(x=425,y=110)
      mb=Menubutton(root2,text="\/",relief=RAISED)
      mb.grid()
      mb.menu = Menu ( mb, tearoff = 0 )
      mb["menu"] = mb.menu
      v=h.keys()
      var=StringVar()
      for w in range(len(v)):
            mb.menu.add_radiobutton(label=v[w],variable=var,value=v[w],command=lambda:button(var.get()))
      mb.place(x=616,y=87)
      global m1
      e='Hi'
      Button(root2,text='Vieworders',font=('Consolas',10),command=vieworders).place(x=940,y=85)
      Button(root2,text="Log Out",font=('Consolas',10),command=lambda:main(root2)).place(x=870,y=85)
      Label(root2,text="Call:2224 5363",font=('Consolas',15),bg='SkyBlue1').place(x=705,y=85)
      Label(root2,text="All India Delivery",font=('Consolas',15),bg='SkyBlue1').place(x=10,y=85)
      Label(root2,text="Top Picks",font=('Consolas',30),bg='SkyBlue1').place(x=400,y=135)
      Label(root2,text='Annual Flowering Plants',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=75,y=190)
      Label(root2,text='Seosonal Plants',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=440,y=190)
      Label(root2,text='Gift Plants',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=770,y=190)
      Label(root2,text='Seeds and Bulbs',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=120,y=415)
      Label(root2,text='Pots and Planters',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=420,y=415)
      Label(root2,text='Fertilizers',height=2,font=('Consolas',15),bg='SkyBlue1').place(x=760,y=415)
      Button(root2,text='Click for more...',command=lambda:afp(root2),bg='yellow3').place(x=180,y=375)
      Button(root2,text='Click for more...',command=lambda:sp(root2),bg='yellow3').place(x=490,y=375)
      Button(root2,text='Click for more...',command=lambda:gp(root2),bg='yellow3').place(x=820,y=375)
      Button(root2,text='Click for more...',command=lambda:sb(root2),bg='yellow3').place(x=180,y=600)
      Button(root2,text='Click for more...',command=lambda:pp(root2),bg='yellow3').place(x=515,y=600)
      Button(root2,text='Click for more...',command=lambda:fz(root2),bg='yellow3').place(x=820,y=600)
      filename=PhotoImage(file = "Hibiscus-Dwarf1.gif")
      image=Button(root2,image=filename,command=lambda:button("Hibiscus-Dwarf"))
      image.place(x=30, y=250)
      filename1=PhotoImage(file = "Peace-rose1.gif")
      image1=Button(root2,image=filename1,command=lambda:button("Peace-rose"))
      image1.place(x=200, y=250)
      filename2=PhotoImage(file = "Aster amellus1.gif")
      image2=Button(root2,image=filename2,command=lambda:button("Aster amellus"))
      image2.place(x=380, y=250)
      filename3=PhotoImage(file = "Zinnia plant1.gif")
      image3=Button(root2,image=filename3,command=lambda:button("Zinnia plant"))
      image3.place(x=505, y=250)
      filename4=PhotoImage(file = "Pachira Plant1.gif")
      image4=Button(root2,image=filename4,command=lambda:button("Pachira Plant"))
      image4.place(x=680, y=250)
      filename5=PhotoImage(file = "Pink anthurium1.gif")
      image5=Button(root2,image=filename5,command=lambda:button("Pink anthurium"))
      image5.place(x=830, y=250)
      filename6=PhotoImage(file = "Brussels sprout1.gif")
      image6=Button(root2,image=filename6,command=lambda:button("Brussels sprout"))
      image6.place(x=60, y=470)
      filename7=PhotoImage(file = "Litchi chinensis1.gif")
      image7=Button(root2,image=filename7,command=lambda:button("Litchi chinensis"))
      image7.place(x=200, y=470)
      filename8=PhotoImage(file = "Apple Valley Planter1.gif")
      image8=Button(root2,image=filename8,command=lambda:button("Apple Valley Planter"))
      image8.place(x=390, y=470)
      filename9=PhotoImage(file = "Lavender Planter1.gif")
      image9=Button(root2,image=filename9,command=lambda:button("Lavender Planter"))
      image9.place(x=535, y=470)
      filename10=PhotoImage(file = "Cow Manure1.gif")
      image10=Button(root2,image=filename10,command=lambda:button("Cow Manure"))
      image10.place(x=690, y=470)
      filename11=PhotoImage(file = "Green Gold - Organic1.gif")
      image11=Button(root2,image=filename11,command=lambda:button("Green Gold - Organic"))
      image11.place(x=840, y=470)
      root2.mainloop()
def modify():
    e=Toplevel()
    e.title('Modify')
    e.geometry('1000x1000')
    e.configure(bg='dark salmon')
    image2=PhotoImage(file='add.gif')
    Label(e,image=image2,bg='dark salmon').place(x=250,y=100)
    Label(e,text='Modify',font=('Consolas',25),bg='dark salmon').place(x=350,y=0)
    Button(e,text='Add Plant',font=('Consolas',15),width=20,bg='orange red').place(x=150,y=200)
    Button(e,text='Increase/Decrease Qty',font=('Consolas',15),width=20,bg='orange red').place(x=150,y=500)
    e.mainloop()
def viewuser():
    r=Toplevel()
    r.title('User Information')
    r.geometry('1500x1500')
    r.configure(bg='khaki')
    Label(r,text='User Informations',font=('Consolas',30),bg='khaki').place(x=300,y=0)
    f5=open('Doc.txt','r')
    f6=f5.read()
    Label(r,text=f6,font=('Consolas',15),bg='khaki').place(x=70,y=200)
    Label(r,text='Name',font=('Consolas',15),bg='khaki').place(x=120,y=150)
    Label(r,text='Email ',font=('Consolas',15),bg='khaki').place(x=240,y=150)
    Label(r,text='Phone no.',font=('Consolas',15),bg='khaki').place(x=340,y=150)
    Label(r,text='Adderess',font=('Consolas',15),bg='khaki').place(x=460,y=150)
    Label(r,text='City',font=('Consolas',15),bg='khaki').place(x=590,y=150)
    Label(r,text='Pin',font=('Consolas',15),bg='khaki').place(x=660,y=150)
    Label(r,text='Country',font=('Consolas',15),bg='khaki').place(x=740,y=150)
    Label(r,text='Password',font=('Consolas',15),bg='khaki').place(x=900,y=150)
    r.mainloop()
def Plants(e):
    e.destroy()
    w=Toplevel()
    a9=StringVar()
    b3=StringVar()
    def login(var1):
        if var1.get()==1:
            filefile=open('Doc.txt','r')
            m13=a9.get()
            m14=b3.get()
            f=filefile.readlines()
            for i in f:
                i=i.rstrip()
                l=i.split(',')
                print l
                if l[2]==m13 and l[9]==m14:
                      z=tkMessageBox.showinfo('Success!',"Mail id exists")
                      if z=='ok':
                          afterlogin(w)
            else:
                tkMessageBox.showerror('Invalid','Invalid Username')
        elif var1.get()==0:
            f2=open('admin.txt','r')
            m14=a9.get()
            m15=b3.get()
            f3=f2.readlines()
            if f3[0].rstrip()==m14 and f3[1].rstrip()==m15 :
                w.destroy()
                w1=Toplevel()
                w1.title('Admin')
                w1.geometry('1000x1000')
                image=PhotoImage(file='orders.gif')
                image1=PhotoImage(file='address.gif')
                Label(w1,image=image1).place(x=670,y=75)
                Label(w1,image=image).place(x=190,y=75)
                Label(w1,text='Admin information',font=('Consolas',25)).place(x=350,y=0)
                Button(w1,text='View user data',font=('Consolas',15),width=20,command=viewuser).place(x=350,y=500)
                Button(w1,text='Modify Plants',width=20,font=('Consolas',15),command=modify).place(x=600,y=200)
                Button(w1,text='View Orders',width=20,font=('Consolas',15),command=vieworders).place(x=150,y=200)
                w1.mainloop()
            else:
                tkMessageBox.showerror('Invalid','Invalid username or password')
                print f3[0],f3[1],len(f3[0]),len(f3[1])

    
    w.geometry('1000x800')
    w.configure(bg='tan1')
    Label(w,text='Returning Customer',font=('Consolas',35),bg='tan1').place(x=510,y=0)
    Label(w,text='New Customer',font=('Consolas',35),bg='tan1').place(x=65,y=0)
    Label(w,text="Register Account",font=('Consolas',25),bg='tan1').place(x=75,y=80)
    var1=IntVar('')
    Radiobutton(w,text="Admin",value=0,variable=var1,font=('Consolas',25),bg='tan1').place(x=590,y=80)
    Radiobutton(w,text="User",variable=var1,value=1,font=('Consolas',25),bg='tan1').place(x=770,y=80)
    Label(w,text='E-Mail Address',font=('Consolas',20),bg='tan1').place(x=510,y=150)
    Entry(w,width=35,textvariable=a9).place(x=750,y=165)
    Label(w,text='Password',font=('Consolas',20),bg='tan1').place(x=510,y=200)
    Entry(w,width=35,show='*',textvariable=b3).place(x=750,y=215)
    Button(w,text='Login',bg='SteelBlue2',font=('Consolas',15),command=lambda:login(var1)).place(x=670,y=320)
    Label(w,text='By creating an account you will be able',font=('Consolas',15),bg='tan1').place(x=20,y=130)
    Label(w,text="to shop faster, be up to date on an",font=('Consolas',15),bg='tan1').place(x=20,y=160)
    Label(w,text="order's status, and keep track of the",font=('Consolas',15),bg='tan1').place(x=20,y=190)
    Label(w,text="orders you have previously made.",font=('Consolas',15),bg='tan1').place(x=20,y=220)
    Button(w,text='Continue',font=('Consolas',15),command=lambda:signup(w),bg='SteelBlue2').place(x=150,y=260)
    Button(w,text="Continue as Guest..",bg='SteelBlue2',font=("Consolas",15),command=lambda:main(w)).place(x=350,y=400)
    w.mainloop()
def afterlogout():
    a=Toplevel()
    a.geometry("500x500")
    Label(a,text="Account Logout",font=('Consolas',35)).place(x=65,y=0)
    Label(a,text="You have been logged off your account.It is",font=('Consolas',15)).place(x=0,y=75)
    Label(a,text="now safe to leave the computer.Your shopping",font=('Consolas',15)).place(x=0,y=105)
    Label(a,text="cart has been saved,the items inside it will",font=('Consolas',15)).place(x=0,y=135)
    Label(a,text="be restored whenever you log back into",font=('Consolas',15)).place(x=0,y=165)
    Label(a,text="your account.",font=('Consolas',15)).place(x=0,y=195)
    Button(a,text="quit",font=('Consolas',15),command=quit()).place(x=210,y=250)
    a.mainloop()


def Logout(a):
    a.destroy()
    e=Toplevel()
    e.configure(background='pale goldenrod')
    e.geometry('720x720')
    Label(e,text='Thank You for Buying!',font=('Cambria',35),bg='pale goldenrod').place(x=100,y=300)
    Button(e,text='Logout',font=('Cambria',15),command=afterlogout).place(x=500,y=500)
    e.mainloop()

def vieworders():
    global c;global d;global k;global cr
    global Q1;global Q;global buy;global D
    if len(buy)==0:
        filename=open('Name.txt',"a+")
        a=filename.read()
        kk=a.split(',')
        for n in range(len(kk)):
            if n>0 and n<len(kk)-1:
                a=kk[n].split(',')
                buy.append(a[1])
                Q.append(a[2])
            else:
                continue
    vieword=Toplevel()
    vieword.geometry("650x900")
    Label(vieword,text="Order History",font=('Consolas',35)).place(x=125,y=0)
    Label(vieword,text="S.No",font=('Consolas',25)).place(x=10,y=85)
    Label(vieword,text="Product",font=('Consolas',25)).place(x=110,y=85)
    Label(vieword,text="Product Details",font=('Consolas',25)).place(x=280,y=85)
    Label(vieword,text="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ").place(x=0,y=120)
    Label(vieword,text="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ").place(x=0,y=60)
    sm=0;tp=0
    for im in range(c):
        Label(vieword,text=im+1,font=('Consolas',25)).place(x=30,y=145+(im*65))
        Label(vieword,text="Name:"+d1[im],font=('Consolas',10)).place(x=260,y=137+(im*65))
        Label(vieword,text="Quantity:"+str(Q1[im]),font=('Consolas',10)).place(x=490,y=137+(im*65))
        Label(vieword,text="Total Price:Rs "+str(int(Q1[im])*P[buy[im]]),font=('Consolas',10)).place(x=340,y=170+(im*65))
        Label(vieword,text="Unit Price:Rs "+str(P[buy[im]]),font=('Consolas',10)).place(x=410,y=155+(im*65))
        Label(vieword,text="Plant Id:"+D[buy[im]],font=('Consolas',10)).place(x=290,y=155+(im*65))
        Label(vieword,text="Total Price:Rs "+str(int(Q1[im])*P[buy[im]]),font=('Consolas',10)).place(x=340,y=170+(im*65))
        Label(vieword,text="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ").place(x=0,y=185+(im*65))
        for pm in range(4):
            jm=70
            if pm==0:
                sm=0
            elif pm==1:
                sm=90
            elif pm==2:
                sm=250
            elif pm==3:
                sm=580
            while jm<(181+(im*65)):
                Label(vieword,text="|").place(x=sm,y=jm)
                jm+=10
        Label(vieword,text=im+1,font=('Consolas',25)).place(x=30,y=(145+(im*65))) 
    vieword.mainloop()

    
def get():
    print b.get()
def buynow(x):
    global c1;global d1;global k
    global Q;global Q1;global c
    print x;print k.get()
    Q[x]=k.get()
    buy.append(x)
    Q1.append(k.get())
    A[x]==int(A[x])-int(k.get())
    print Q1
    c+=1
    d1.append(x)
    a=Toplevel()
    a.configure(bg='powder blue')
    a.geometry("1000x1000")
    Label(a,text="Shopping Cart",font=('Consolas',35),bg='powder blue').place(x=125,y=0)
    Label(a,text="S.No",font=('Consolas',25),bg='powder blue').place(x=10,y=85)
    Label(a,text="Product",font=('Consolas',25),bg='powder blue').place(x=110,y=85)
    Label(a,text="Product Details",font=('Consolas',25),bg='powder blue').place(x=280,y=85)
    Label(a,text="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",bg='powder blue').place(x=0,y=120)
    Label(a,text="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",bg='powder blue').place(x=0,y=60)
    s=0
    tp=0
    for i in range(c):
        sf=[]
        Label(a,text=i+1,font=('Consolas',25)).place(x=30,y=145+(i*65))
        Label(a,text="Name:"+d1[i],font=('Consolas',10),bg='powder blue').place(x=260,y=137+(i*65))
        Label(a,text="Quantity:"+str(Q1[i]),font=('Consolas',10),bg='powder blue').place(x=490,y=137+(i*65))
        Label(a,text="Plant Id:"+D[x],font=('Consolas',10),bg='powder blue').place(x=290,y=155+(i*65))
        Label(a,text="Unit Price:Rs "+str(P[x]),font=('Consolas',10),bg='powder blue').place(x=410,y=155+(i*65))
        Label(a,text="Total Price:Rs "+str(int(Q1[i])*P[x]),font=('Consolas',10),bg='powder blue').place(x=340,y=170+(i*65))
        Label(a,text="_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ",bg='powder blue').place(x=0,y=185+(i*65))
        Button(a,text='Proceed to Checkout>>>',font=('Consolas',15),command=lambda:Logout(a)).place(x=600,y=600)
        Button(a,text='<<<Continue Shopping',font=('Consolas',15),command=lambda:afterlogin(a)).place(x=0,y=600)
        sff=''
        for k in range(len(sf)):
            if k==len(sf)-1:
                sff+=sf[k]+'.'
        for p1 in range(4):
            j=70
            if p1==0:
                s=0
            elif p1==1:
                s=90
            elif p1==2:
                s=250
            elif p1==3:
                s=580
            while j<(181+(i*65)):
                Label(a,text="|",bg='powder blue').place(x=s,y=j)
                j+=10
        Label(a,text=i+1,font=('Consolas',25),bg='powder blue').place(x=30,y=(145+(i*65)))
    filename=open('name.txt','a+')
    filename.write(sff)
    filename.close()
    a.mainloop()
def update1():
    global password;global confirmpassword;global s
    global l;global m
    password[s]=l.get();confirmpassword[s]=m.get()
def update(x):
    global s;global n;global n2;global n3;global n4;global n5;global n6;global n7;global n8;global n9;global n10;global n11
    global city;global postcode;global country;global state;global password;global confirmpassword;global firstname;global lastname;global email;global address;global telephone
    if x=="acc":
        firstnamer[s]=n.get();emailr[s]=n3.get();lastnamer[s]=n2.get();telephoner[s]=n4.get()
    elif x=="add":
        addressr[s]=n5.get();cityr[s]=n6.get();postcode[s]=n7.get();countryr[s]=n8.get();state[s]=n9.get()
    elif x=="pass":
        password[s]=n11.get()
    elif x=="whole":
        firstnamer[s]=n.get();emailr[s]=n3.get();lastnamer[s]=n2.get();telephoner[s]=n4.get(); password[s]=n11.get();addressr[s]=n5.get();cityr[s]=n6.get();postcode[s]=n7.get();countryr[s]=n8.get();state[s]=n9.get()
    print firstname,lastname,telephone,email,address,city,postcode,country,state,password,confirmpassword

root1 = Tk()
root1.geometry('1400x1400')
image1 = PhotoImage(file='besthdwallpaperinnature3d.gif')
image2=PhotoImage(file='besthdwallpaperinnature3d.gif')
Label(root1,image=image1,fg='Black').place(x=0,y=0)
Button(root1,text='Advance --->',compound=CENTER,image=image2,font=('Consolas',15,),height=50,width=0,command=lambda:main(root1),fg='White').place(x=0,y=610)
root1.mainloop()


